EspeceIdentifiee:
    type: entity
    table: espece_identifiee
    indexes:
        ce_cle_etrangere79:
            columns:
                - referentiel_taxon_fk
        ce_cle_etrangere75:
            columns:
                - date_precision_voc_fk
        ce_cle_etrangere77:
            columns:
                - lot_materiel_ext_fk
        ce_cle_etrangere78:
            columns:
                - lot_materiel_fk
        ce_cle_etrangere76:
            columns:
                - sequence_assemblee_ext_fk
        ce_cle_etrangere74:
            columns:
                - critere_identification_voc_fk
        ce_cle_etrangere80:
            columns:
                - individu_fk
        ce_cle_etrangere81:
            columns:
                - sequence_assemblee_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateIdentification:
            type: date
            nullable: true
            column: date_identification
        commentaireEspId:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: commentaire_esp_id
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        critereentificationVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                critere_identification_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        datePrecisionVocFk:
            targetEntity: Voc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                date_precision_voc_fk:
                    referencedColumnName: id
            orphanRemoval: false
        sequenceAssembleeExtFk:
            targetEntity: SequenceAssembleeExt
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sequence_assemblee_ext_fk:
                    referencedColumnName: id
            orphanRemoval: false
        lotMaterielExtFk:
            targetEntity: LotMaterielExt
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lot_materiel_ext_fk:
                    referencedColumnName: id
            orphanRemoval: false
        lotMaterielFk:
            targetEntity: LotMateriel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lot_materiel_fk:
                    referencedColumnName: id
            orphanRemoval: false
        referentielTaxonFk:
            targetEntity: ReferentielTaxon
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                referentiel_taxon_fk:
                    referencedColumnName: id
            orphanRemoval: false
        individuFk:
            targetEntity: Individu
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                individu_fk:
                    referencedColumnName: id
            orphanRemoval: false
        sequenceAssembleeFk:
            targetEntity: SequenceAssemblee
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sequence_assemblee_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
